export const products = [
  {
    id: "assorted-diya",
    name: "Assorted Diya Candles",
    category: "Traditional Collection",
    description:
      "Beautiful diya-shaped candles in assorted colors, perfect for festive occasions and traditional celebrations. Each piece is carefully handcrafted to capture the essence of traditional diyas with a modern twist.",
    price: "₹399 - ₹999",
    features: [
      "Available in sets of 3, 5, or 7 diyas",
      "Premium soy wax blend",
      "25-30 hours burn time per diya",
      "Traditional designs with contemporary colors",
      "Perfect for Diwali and festive decorations",
    ],
    images: [
      "/images/AssortedDiya/AsD1.jpg",
      "/images/AssortedDiya/AsD2.jpg",
      "/images/AssortedDiya/AsD3.jpg",
    ],
    popularity: 80,
  },
  {
    id: "chai-biscuit",
    name: "Chai Biscuit Candles",
    category: "Nostalgia Collection",
    description:
      "Charming candles shaped like classic chai biscuits, bringing back memories of tea-time conversations. Each candle perfectly replicates the beloved biscuit design.",
    price: "₹449 - ₹799",
    features: [
      "Authentic biscuit design",
      "Chai-inspired fragrance",
      "Natural soy wax",
      "20-25 hours burn time",
      "Available in different biscuit varieties",
    ],
    images: [
      "/images/ChaiBiscuit/chai-biscuit-1.jpg",
      "/images/ChaiBiscuit/chai-biscuit-2.jpg",
      "/images/ChaiBiscuit/chai-biscuit-3.jpg",
      "/images/ChaiBiscuit/chai-biscuit-4.jpg",
    ],
    popularity: 95,
  },
  {
    id: "coffee",
    name: "Coffee Cup Candles",
    category: "Modern Collection",
    description:
      "Elegant coffee cup-shaped candles with rich coffee fragrance. Perfect for coffee lovers and modern home décor enthusiasts.",
    price: "₹549 - ₹849",
    features: [
      "Premium coffee fragrance",
      "Reusable ceramic cup design",
      "30-35 hours burn time",
      "Natural wax blend",
      "Available in various cup styles",
    ],
    images: [
      "/images/Coffee/BlackCoffee1.jpg",
      "/images/Coffee/BlackCoffee2.jpg",
      "/images/Coffee/BlackCoffee3.jpg",
    ],
    popularity: 90,
  },
  {
    id: "dalgona-coffee",
    name: "Dalgona Coffee Candles",
    category: "Trendy Collection",
    description:
      "Inspired by the viral Dalgona coffee trend, these layered candles capture the visual appeal of the popular beverage in candle form.",
    price: "₹649",
    features: [
      "Layered design mimicking Dalgona coffee",
      "Coffee and cream fragrance blend",
      "35 hours burn time",
      "Decorative glass container",
      "Perfect for coffee table décor",
    ],
    images: [
      "/images/DalgonaCoffee/dalgona1.jpg",
      "/images/DalgonaCoffee/dalgona2.jpg",
    ],
    popularity: 87,
  },
  {
    id: "laddu-candles",
    name: "Laddu Candles",
    category: "Traditional Collection",
    description:
      "Beautifully crafted candles in the shape of traditional laddus, bringing a touch of Indian sweetness to your décor.",
    price: "₹399 - ₹699",
    features: [
      "Authentic laddu texture",
      "Sweet vanilla fragrance",
      "Available in different sizes",
      "20-25 hours burn time",
      "Perfect for festive gifting",
    ],
    images: [
      "/images/LadduCandles/ladoo-candle-1.jpg",
      "/images/LadduCandles/ladoo-candle-2.jpg",
      "/images/LadduCandles/ladoo-candle-3.jpg",
      "/images/LadduCandles/ladoo-candle-4.jpg",
    ],
    popularity: 92,
  },
  {
    id: "peony-candles",
    name: "Peony Candles",
    category: "Floral Collection",
    description:
      "Delicate peony-shaped candles with intricate petals, bringing the beauty of spring flowers to your space.",
    price: "₹749",
    features: [
      "Detailed peony flower design",
      "Fresh floral fragrance",
      "Premium wax blend",
      "30 hours burn time",
      "Available in soft Purple and white",
    ],
    images: [
      "/images/PeonyPurple/PeonyPurple1.jpg",
      "/images/PeonyPurple/PeonyPurple2.jpg",
      "/images/PeonyPurple/PeonyPurple3.jpg",
      "/images/PeonyPurple/PeonyPurple4.jpg",
      "/images/PeonyWhite/PeonyWhite1.jpg",
      "/images/PeonyWhite/PeonyWhite2.jpg",
      "/images/PeonyWhite/PeonyWhite3.jpg",
    ],
    popularity: 83,
  },
  {
    id: "bouquet-collection",
    name: "Bouquet Collection",
    variants: ["Pink", "Purple", "White"],
    category: "Luxury Collection",
    description:
      "Exquisite bouquet-shaped candles available in different color themes. Each piece is crafted to look like a miniature flower arrangement.",
    price: "₹899 - ₹1499",
    features: [
      "Multiple flower designs in each bouquet",
      "Premium floral fragrances",
      "40-45 hours burn time",
      "Decorative container included",
      "Perfect for special occasions",
    ],
    images: [
      "/images/PinkBouquet/pbq1.jpg",
      "/images/PinkBouquet/pbq2.jpg",
      "/images/PinkBouquet/pbq3.jpg",
      "/images/PinkBouquet/pbq4.jpg",
      "/images/PurpleBouquet/bqt1.jpg",
      "/images/PurpleBouquet/bqt2.jpg",
      "/images/PurpleBouquet/bqt3.jpg",
      
    ],
    popularity: 88,
  },
  // {
  //   id: "promotional-misc",
  //   name: "Promotional & Miscellaneous",
  //   category: "Special Collection",
  //   description: "Special edition and promotional candles created for various occasions and corporate gifting.",
  //   price: "Contact for pricing",
  //   features: [
  //     "Customizable designs",
  //     "Bulk order options",
  //     "Corporate branding available",
  //     "Various sizes and shapes",
  //     "Custom fragrance options"
  //   ],
  //   images: []
  // },
  {
    id: "urli-candles",
    name: "Urli Candles",
    category: "Traditional Collection",
    description:
      "Traditional urli-shaped candles that bring elegance and cultural touch to your space.",
    price: "₹649 - ₹949",
    features: [
      "Classic urli design",
      "Traditional patterns",
      "35-40 hours burn time",
      "Available in different sizes",
      "Perfect for traditional décor",
    ],
    images: [
      "/images/Urli/urli-candle-1.jpg",
      "/images/Urli/urli-candle-2.jpg",
      "/images/Urli/urli-candle-3.jpg",
    ],
    popularity: 93,
  },
  {
    id: "wax-tablets",
    name: "Wax Tablets",
    category: "Modern Collection",
    description:
      "Modern wax tablets for oil burners and warmers, available in various fragrances.",
    price: "₹299 - ₹499",
    features: [
      "Easy to use design",
      "Multiple fragrance options",
      "Long-lasting aroma",
      "Pack of 6 or 12 tablets",
      "Compatible with all warmers",
    ],
    images: [
      "/images/Wax Tablets/wt1.jpg",
      "/images/Wax Tablets/wt2.jpg",
      "/images/Wax Tablets/wt3.jpg",
      "/images/Wax Tablets/wt4.jpg",
      "/images/Wax Tablets/wt5.jpg",
    ],
    popularity: 90,
  },
  {
    id: "welcome-candles",
    name: "Welcome Candles",
    category: "Occasion Collection",
    description:
      "Specially designed welcome candles for events and celebrations, perfect for creating a warm atmosphere.",
    price: "₹499 - ₹799",
    features: [
      "Elegant welcome designs",
      "Customizable messages",
      "25-30 hours burn time",
      "Perfect for events",
      "Available in sets",
    ],
    images: [
      "/images/Welcome Candles/wc1.jpg",
      "/images/Welcome Candles/wc2.jpg",
      "/images/Welcome Candles/wc3.jpg",
      "/images/Welcome Candles/wc4.jpg",
    ],
    popularity: 86,
  },
  {
    id: "flower-collection",
    name: "Single Flower Candles",
    variants: ["White Flower", "Yellow Flower"],
    category: "Floral Collection",
    description:
      "Beautiful single flower candles that add a touch of natural beauty to any space.",
    price: "₹449 - ₹649",
    features: [
      "Realistic flower designs",
      "Natural floral fragrances",
      "25-30 hours burn time",
      "Perfect for table settings",
      "Available in multiple colors",
    ],
    images: [
      "/images/wtflw/wtflw.jpg",
      "/images/wtflw/wtflw1.jpg",
      "/images/wtflw/wtflw2.jpg",
      "/images/wtflw/wtflw3.jpg",
      "/images/wtflw/wtflw4.jpg",
      "/images/yflw/yflw.jpg",
      "/images/yflw/yflw1.jpg",
      "/images/yflw/yflw2.jpg",
      "/images/yflw/yflw3.jpg",
    ],
    popularity: 89,
  },
];

export const categories = [
  "Traditional Collection",
  "Modern Collection",
  "Floral Collection",
  "Luxury Collection",
  "Nostalgia Collection",
  "Trendy Collection",
  "Occasion Collection",
  "Special Collection",
];
